version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  publisher:
    build:
      context: .
      dockerfile: publisher/Dockerfile
    depends_on:
      - redis
      - subscriber
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./publisher:/app/publisher
      - /app/node_modules

  subscriber:
    build:
      context: .
      dockerfile: subscriber/Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
